services:
  bot:
    image: 'burenotti/bruhsty:latest'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    command: [ "python", "-m", "bruhsty" ]
    depends_on:
      - postgres
      - redis
    networks:
      - postgres
      - redis

  postgres:
    image: 'postgres:16-alpine'
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=bot
      - POSTGRES_PASSWORD=bot
      - POSTGRES_DB=bot
    networks:
      - postgres

  redis:
    image: 'redis:7.2.1'
    ports:
      - 6379:6379
    expose:
      - 6379
    networks:
      - redis

networks:
  postgres:
  redis: